server:
  port: 8081

spring:
  application:
    name: wms

  profiles:
    active: uat

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true

    hibernate:
      ddl-auto: create

    show-sql: true

jwt:
  expiration: 10d
